# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caa963a64c430385bf3b1ca188556882b1a635c877fe06208097b80d6ad66a4e73df86d5f72f95d5f357b99cdd137c0d1aff26e56632e83afe60ebe86f2851ae

test:
  secret_key_base: e263063abc4cf3f03096b852217cb17ea27b7b7866e4481a5154ca6b1c3917f1fe27f0ead7288a88c3c541cd4adbaa459ffc785b3c78b84178a39b131b61c82b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: e263063abc4cf3f03096b852217cb17ea27b7b7866e4481a5154ca6b1c3917f1fe27f0ead7288a88c3c541cd4adbaa459ffc785b3c78b84178a39b131b61c82b
